[package]
name = "fizzy"
description = "intergalactic sanctioned drinking game"
version = "0.0.1"
edition = "2024"
authors = ["Andrew Pennebaker <andrew.pennebaker@gmail.com>"]
license = "BSD-2-Clause"

[dependencies]
ctor = { version = "1.0.13", optional = true }
die = { version = "0.2.0", optional = true }
tinyrick = { version = "0.0.30", optional = true }
tinyrick_extras = { version = "0.0.20", optional = true, path = ".." }
tinyrick_macros = { version = "0.0.6", optional = true }
tinyrick_models = { version = "0.0.3", optional = true }

[features]
letmeout = [
    "ctor",
    "die",
    "tinyrick",
    "tinyrick_extras",
    "tinyrick_macros",
    "tinyrick_models",
]

[lib]
path = "src/lib/fizzy.rs"

[[bin]]
name = "fizzbuzz"
path = "src/bin/fizzbuzz.rs"

[[bin]]
name = "tinyrick"
path = "tinyrick.rs"
required-features = ["letmeout"]
