#!/bin/sh
set -e

cargo install --force \
    cargo-audit \
    cargo-cache \
    cargo-edit \
    crit@0.0.9 \
    cross@0.2.5 \
    tinyrick@0.0.16 \
    unmake@0.0.21

rustup component add \
    clippy \
    rustfmt
